### ISSUE TITLE
Files are only exporting to the FP folder, the rest are empty.

### ISSUE THREAD

**Issue by ctparadise** [Helicer/batch-text2speech#13]
As a user I expect it to export the audio to all folders, instead it is only exporting to the FP folder and all others are empty.

**Comment by ctparadise** [comment]
[Bug.txt](https://github.com/Helicer/batch-text2speech/files/4490348/Bug.txt)

**Comment by ctparadise** [comment]
[example_chinese.txt](https://github.com/Helicer/batch-text2speech/files/4490354/example_chinese.txt)

**Comment by ctparadise** [comment]
./tts.py -m csv -f example_chinese.csv -v1 Zhiyu -v2 Joanna -v2e neural -v

**Comment by Helicer** [comment]
Your AWS region was set to `us-east-2`. That AWS region does not support neural voices yet. We used `aws configure` to set the region to `us-east-1` and now the files export.
