### ISSUE TITLE
Should I remove the "simpletext" mode? 

### ISSUE THREAD

**Issue by Helicer** [Helicer/batch-text2speech#3]
This is the mode where you put in a single phrase per line in `sentences.txt` and it outputs the phrase. I believe we could add it back later if needed. 
The benefit to removing it: Simply code, allow us to release features easier.

**Comment by Helicer** [comment]
@ctparadise What do you think?

**Comment by ctparadise** [comment]
We can remove simple text mode, but we should create a csv mode that does the same thing. It's nice to be able to create single language + pause sentences.

**Comment by Helicer** [comment]
Ok makes sense. Thanks.

**Comment by Helicer** [comment]
Opened #26  for this.
