### ISSUE TITLE
Set track # starting # 

### ISSUE THREAD

**Issue by ctparadise** [Helicer/batch-text2speech#9]
As a user exporting numbered mp3s, I'd like to input the starting number in CSV. Why? - in case a big batch crashes 1/2 way through, I can start where it crashed and continue numbering where it left off. BONUS - perhaps if the CSV field = NO it doesn't number the tracks, and if it's any number (including 0) it will number tracks starting with that. Why? - There are times when it's useful to have numbered tracks and times when it's not, this gives the user the option to export with, without, and control where numbering starts.

**Comment by Helicer** [comment]
Completed with Issue #24
